# Generated by Django 4.2.3 on 2024-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_display_ads_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_ads',
            name='ads_url',
            field=models.URLField(default=None),
        ),
    ]
