# Generated by Django 4.2.3 on 2024-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('creator', models.CharField(max_length=300)),
                ('phone_contact', models.CharField(default='090988777877', max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
