# Generated by Django 4.2.3 on 2024-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transactionpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transactionPin',
            field=models.IntegerField(default='0000'),
        ),
        migrations.DeleteModel(
            name='TransactionPin',
        ),
    ]
