# Generated by Django 4.2.3 on 2024-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_transactionpin_delete_transactionpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transactionPin',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
