# Generated by Django 4.2.3 on 2024-04-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_transactionpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transactionPin',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
