# Generated by Django 4.2.3 on 2024-04-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_transactionpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transactionPin',
            field=models.IntegerField(default=0),
        ),
    ]
