# Generated by Django 4.2.3 on 2024-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_transactionpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_identification_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_tag',
            field=models.CharField(default='OMMCSL', max_length=200),
        ),
    ]
