# Generated by Django 4.2.3 on 2024-06-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_client_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='next_of_kin_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin_full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin_phone_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='your first name', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='your first name', editable=False, max_length=150),
        ),
    ]
