# Generated by Django 4.2.3 on 2024-04-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_for_share',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='payment_for_share',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment_for_share',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='payment_for_share',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0', editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='payment_for_share',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
